version: '3.7'

services:
  api-mini-project-service:
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - mynetwork
    depends_on:
      - mysql-service
  
  mysql-service:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306
    volumes:
      - D:\Kuliah\Kampus_Merdeka\Alterra_Academy_SI\myvolume:/var/lib/mysql
      - ./mysql/schema.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
